spring.application.name=limit-services

# spring.cloud.config.enabled=false
# limit-service.minimum=22
# limit-service.maximum=98

# spring.cloud.config.server.native.search-locations=file:///Users/radhe/Desktop/Learning/Spring-Boot/config-repo
spring.profiles.active=qa
spring.cloud.config.profile=qa

spring.config.import=optional:configserver:http://localhost:8888